### ISSUE TITLE
Add support for aurora services installer

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Iamlooker/Droid-ify#104]
Installation via aurora services the simplest option among the existing ones, as the service is activated by using ota patch without root. It's more comfortable than shizuku. 

https://gitlab.com/AuroraOSS/AuroraServices

**Comment by freMea** [comment]
Good idea but aurora services seem buggy according to this [recent comment](https://forum.xda-developers.com/t/app-5-0-aurora-droid-f-droid-client-july-22.3932663/post-87041715). Unless the bug comes from auroradroid.

Plus aurora services does not mention an API.

As long I’m notified of apps update, I’m ok to install them manually meanwhile a background installer services be implemented or not.

**Comment by Iamlooker** [comment]
Yes, I don't plan on adding support for Aurora Installer Service, because any bug in that app can cause behavioral and security issues. Also I don't plan to make a alternative myself for time being, meanwhile you can use Shizuku Installer it is basically root installer with/without root.

I currently don't plan on working on new projects, even though I announced so on Telegram, I will only be working on select number of projects for now.
