### ISSUE TITLE
Replace dropdown menu with pill

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#130]
The dropdown menu in Droid-ify is quite unique. Google guidelines suggest a pill.

![Screenshot_20221014-230328_Droid-ify](https://user-images.githubusercontent.com/50382414/195944096-39c1d299-abec-4666-9611-52fda0ae8029.png)

![Screenshot_20221014-230600_Neo Store](https://user-images.githubusercontent.com/50382414/195944105-76d369e5-915d-4b9a-96fb-60ce517dedb2.png)

**Comment by Donkey-Doug** [comment]
Another example (without background):

![Screenshot_20221015-003703_LibreTube](https://user-images.githubusercontent.com/50382414/195953707-96f7fab2-fa4d-4858-b1a6-59b346c97d28.png)

**Comment by Donkey-Doug** [comment]
I think a good name for the pill would be "filter" because it is used to filter for categories or repos.

**Comment by Donkey-Doug** [comment]
Actually I think the dropdown menu and pill are not needed. I don't really see the benefit of filtering by category or repo anyway. Perhaps just add "filter" to the 3 dots menu because I think it is not a commonly used function.

**Comment by vertigo220** [comment]
IMO just because Google recommends something a particular way doesn't make it best. They're known for making lots of bad UI/UX decisions and not listening to users, and have destroyed a fair amount of products because of it. They also don't always follow their own guidelines. By switching to a pill (is that the official word for that?) it only takes up more space, whereas right now it's just an icon sitting in what would otherwise be blank space next to the 3 dots and refresh icons, which is also why I think moving it into the 3 dots isn't really necessary, and may make a feature that, as you say, is likely not commonly used, even less used because users may not realize or may forget that it's even there. I'd understand if there were more useful things to take its place, but as it is, it's not in the way or taking up space that would otherwise be useful for something else.

**Comment by Donkey-Doug** [comment]
> By switching to a pill (is that the official word for that?) it only takes up more space, whereas right now it's just an icon sitting in what would otherwise be blank space next to the 3 dots and refresh icons

No, I am talking about the "all applications" in the dropdown menu (see screenshot). So it won't take up more space.

**Comment by Iamlooker** [comment]
We have tried switiching to pill based system in alpha builds and that didn't work out. It not really welcomed by most including me, I will close this issue fod now and maybe in future we can find a better way.

**Comment by Donkey-Doug** [comment]
OK. Would it be possible for me to try the alpha, just to see what it is like?

**Comment by Iamlooker** [comment]
> OK. Would it be possible for me to try the alpha, just to see what it is like?

Sure, in the telegram group.

**Comment by Donkey-Doug** [comment]
So the pill in the alpha spans the whole display. I meant a small pill that does not use the entire width of the display.

**Comment by Iamlooker** [comment]
> Isn't this issue superseded by #273, as a redesign of the whole search bar is planned? @Iamlooker

Yup, thanks for reminding me
