### ISSUE TITLE
Group links and donate section

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#15]
Currently the links and donate sections are seperated, which makes the ui look cluttered. I suggest grouping them.

![Screenshot_20211008-134031_Droid-ify_1](https://user-images.githubusercontent.com/50382414/136550858-60b817de-9cec-42f6-9394-c48add7b59c3.png)

I would call the header "Donate" and provide the link in the subtext. The icon next to donate should also be updated.

**Comment by Iamlooker** [comment]
Thing is that some developers may have multiple methods of donations thats why there is a section for it.

**Comment by another-sapiens** [comment]
Maybe it could be grouped if there's just 1, and the separate section gets triggered only when there's multiple methods listed. Though that could create some inconsistency 🤔

Maybe making the separation a bit less 'separated' could help. Like putting a small label instead of another drop-down when there's more than 1.

**Comment by Iamlooker** [comment]
Hmm am still not that convinced to move them to one.
Maybe I could move them all some another way.

**Comment by dhishkyaon** [comment]
I think its good to keep them separate.
