### ISSUE TITLE
Add option for rounded corners

### ISSUE THREAD

**Issue by BlackRabbit22** [Iamlooker/Droid-ify#28]
Please add an option to enable/disable the classic rounded corners. 
They made the app look much better. 

Thank you.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Ideally, the relevant elements should adhere to the appearance of the system. I believe that dialogues, for instance, certainly are provided by the system.

**Comment by Iamlooker** [comment]
Corner rounding is implemented here 7d4c9793965b348403b6d68fa5ab29bff04ae2be

Its in upward direction, i.e. as shown [here](https://github.com/Iamlooker/Droid-ify/blob/main/metadata/en-US/images/phoneScreenshots/home-light.png)

For Android 12+ it will take the screen corner radius otherwise it will keep 16dp (i.e. as shown in screenshot)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Iamlooker, regarding what I previously stated, does Droid-ify call the Android device frameworks, or does it do what Google's software occasionally does, and utilize a custom library for this?

For me the, the former is definitely more desirable, because solely it adheres to the customisation of my system.

**Comment by Iamlooker** [comment]
Well I dont use any library for corner rounding over there, neither do I call Android Framework, just set a rounded background

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Iamlooker, does that mean that Droid-ify's dialogues, for instance, are custom-drawn boxes with a manually positioned label and masked by a rounded box? I don't believe that that is how they are usually invoked.

**Comment by Iamlooker** [comment]
Naah I meant the toolbar, the dialogs are the default material3 dialogs
