### ISSUE TITLE
Unable to read full repository descriptions

### ISSUE THREAD

**Issue by xandris** [Iamlooker/Droid-ify#65]
Minor nitpick, but repository descriptions in the list of repositories are a single, ellipsized line. That's fine but it would be nice to show the full description on long press in the repository details.

**Comment by Iamlooker** [comment]
Actually repositories can update their description as they are synced from the internet.
I tried to get/make the best possible small description to show while they are not updated, another reason why they get updated is because we don't sync all the repositories by default, we only sync the enabled one to reduce data usage.

I will try to update the description in next release but I don't think I allow syncing of all the unselected repositories.

If you have any more doubts then you can ask me.

**Comment by xandris** [comment]
That makes sense, I just can't read your description. It gets truncated, and the UI doesn't show the full text anywhere.

![Screenshot_20220731-122629.png](https://user-images.githubusercontent.com/1970616/182042053-0d9f7867-fa90-47ab-9da2-f8f375db369c.png)

**Comment by Iamlooker** [comment]
Ooh here you can long click on the enabled repositories to see the whole details about them and you can also edit url and select better mirrors for them

**Comment by Iamlooker** [comment]
![Screenshot_20220801-011343_Droid-ify](https://user-images.githubusercontent.com/60404093/182042562-f343eee0-c387-4606-8ed4-d7e7dffc8dec.png)


Like this

**Comment by xandris** [comment]
Oh, I see the issue. I'm trying to read the descriptions of repositories I don't have enabled so I know if want to enable them. Descriptions don't show on long press for disabled repositories, probably for the reason you stated? But even if you're the one who wrote the description it would still help me decide if I want to enable the repository.

![Screenshot_20220731-124600.png](https://user-images.githubusercontent.com/1970616/182042975-1674a414-272e-4da3-8766-cd383a981159.png)

**Comment by Iamlooker** [comment]
Ooh this, my bad I didn't notice this what!!

I will fix this tomorrow.

**Comment by Iamlooker** [comment]
Thanks for letting me know
