### ISSUE TITLE
Handle links to apps in other repositories

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#88]
**Is your feature request related to a problem? Please describe.**
Droid-ify can handle links to apps only in the official repository. This means you can't follow a link to apt.izzysoft.de within the app.

**Describe the solution you'd like**
Handle links to all repositories activated by the user.

**Comment by Iamlooker** [comment]
This would actually be impossible, as every repository have its own url for showing app info. And I don't think I would be able to add info link for all rhe repositories, the best I can do is to add it for few more repos which are famous.

Because a user can add his/her own repos to the app and they might be a private repo which doesnt even have website.

If you have a different way of implementing this then I would be more then happy to try it 😃

**Comment by yephny** [comment]
@Iamlooker Oh, that's exactly what I meant when I said repositories activated by the user, not added. It'd be a pretty useful feature.

**Comment by Iamlooker** [comment]
What exactly would you like to share?

I can make a simple share for every repo, but it will only open in fdroid clients and not in browser, which is obsolete in my eyes. 

Also if I add links to separate repos, then you won't be able to open them in any FDroid client because they can't handle links for all the repo.

Which means either you can have it shown in the browser or either clients.

**Comment by Iamlooker** [comment]
As I said earlier, not all repo have their own website. You can't open a link into Droidify the link directs to a download page.

If this doesn't seem like a good explanation then please elaborate on your request I didn't understand your request.

**Comment by yephny** [comment]
Okay, then, my request can be specific to Izzy's repository. Take [this link](https://apt.izzysoft.de/fdroid/index/apk/com.gitlab.mudlej.MjPdfReader), for example.

**Comment by Iamlooker** [comment]
Ooh you just want it to show in Droid-ify, okay this shouldn't be that hard.

I will try this and reach you back

**Comment by Iamlooker** [comment]
Added in f6b0c807ac6261b0d07d1bcf12e5d830ad3d9342
