### ISSUE TITLE
[Feature request] Add a progress bar for installing!

### ISSUE THREAD

**Issue by dataprolet** [Iamlooker/Droid-ify#90]
I find it somewhat confusing to update a single app, because it's unclear whether the app is installing/updating in the background after it got downloaded or not. I would like a progress bar similar to the one for downloading and also the button to change from "Update" to "Install" and not use the notification for that.

**Comment by DaniAndTheWeb** [comment]
I think you should change a little bit the feature request since a progress bar for installation on android is quite impossible to make. On the other hand a generic loading animation would be a great idea to show that the app is actually installing

**Comment by dataprolet** [comment]
You're right, I wasn't talking about a progress bar as a notification, but inside the app. Because after hitting the "Update"-button, it's downloading the update which is indicated by a progress bar inside the app, but after that the button goes back to displaying "Update" even though it's installing in the background. Is that understandable?

**Comment by vertigo220** [comment]
Agree. This really confused me at first and I kept hitting the install button, and now I know but it's still a bit confusing because I'm not sure if it's actually doing it or not, especially since if you back out of the app's page before it pops up asking if you want to install it doesn't happen at all.
